version : 2.1
orbs:
  snyk: snyk/snyk@1.7.2

jobs:
  snyk-scan:
    docker:
      - image: circleci/node:latest
    steps:    
      - checkout
      - run: npm install
      - snyk/scan:
          token-variable: SNYK_TOKEN
          command: monitor
          monitor-on-build: false          
        
workflows:
    build-snyk:
        jobs: 
        - snyk-scan
      

